### ISSUE TITLE
Warning about deprecated function

### ISSUE THREAD

**Issue by fuhlig1** [HeavyIonAnalysis/AnalysisTree#10]
Hi,

when compiling the CbmRoot interface to AnalysisTree I get the following warnings abou a deprecated function

```
In file included from /Users/uhlig/software/fair/cbm/cbmroot_git/analysis/common/analysis_tree_converter/CbmConverterManager.cxx:4:
/opt/cbmroot/build/git_fairroot-v18.2.1_fairsoft-jun19p2/include/AnalysisTree/TaskManager.hpp:52:43: warning: 'GetBranchName' is deprecated [-Wdeprecated-declarations]
    cuts_map_.insert(std::make_pair(cuts->GetBranchName(), cuts));
                                          ^
/opt/cbmroot/build/git_fairroot-v18.2.1_fairsoft-jun19p2/include/AnalysisTree/Cuts.hpp:63:5: note: 'GetBranchName' has been explicitly marked deprecated here
  [[deprecated]]
    ^
```

Could you have a look and see if you can fix it.

**Comment by viktorklochkov** [comment]
Dear Florian! 

That is actually expected since I want to remove this function in the next release. The warning is needed to try to remove all usages in all AnalysisTree-based packages before that. 

Cheers,
Viktor

**Comment by fuhlig1** [comment]
Hi @viktorklochkov ,

ok. When do you expect the new implementation to be available? For the time being I will filter the warning on our side.

**Comment by viktorklochkov** [comment]
I think definitely this month. I want to finish with unit tests first

**Comment by viktorklochkov** [comment]
Well, not exactly in time, but can be closed now
