### ISSUE TITLE
TaskManager::AddBranchCut() doesn't work

### ISSUE THREAD

**Issue by mam-mih-val** [HeavyIonAnalysis/AnalysisTree#4]
@viktorklochkov, please check the functionality of branch cuts, beacause  branch cuts don't work at all.

**Comment by viktorklochkov** [comment]
Problem was from other side =) Fixed with

https://git.cbm.gsi.de/pwg-c2f/analysis/flow/-/commit/76c6dc150f2208770fd11e2729687de08d9e3307
