### ISSUE TITLE
misleading readme

### ISSUE THREAD

**Issue by OlegGolosov** [HeavyIonAnalysis/AnalysisTree#44]
You propose to build root from scratch which takes lots of and does not differ from the package you can download in a minute for the most popular linux distributions. The only added value could be specifying the cxx17 flag but there is no mention about it. Moreover AnalysisTree will not compile if you use root installation built with cxx11 if you do not state this explicitly. Again, it is not mentioned in the readme.

**Comment by OlegGolosov** [comment]
the instruction "git clone" looks wonderfull as well

**Comment by viktorklochkov** [comment]
Thanks for the feedback! Should be better now =)
