### ISSUE TITLE
AnalysisTree::GetMassByPdgId()

### ISSUE THREAD

**Issue by mam-mih-val** [HeavyIonAnalysis/AnalysisTree#55]
Dear @viktorklochkov,

Please note, that the current implementation of the function is not really functional and safe. Only 10 particles are coded and nobody checked if the masses are correct. 
Consider the implementation based on TDatabasePDG class from root: 
https://root.cern.ch/doc/master/classTDatabasePDG.html

**Comment by eugene274** [comment]
Do not forget to add ROOT::EG to the dependencies of AT::Core

**Comment by viktorklochkov** [comment]
Dear @mam-mih-val, @eugene274 

I totally agree with your concern! Thank you for reporting!

I invite you to start using version 2, which has many bugs fixed, for example, please check the current implementation of mentioned method:

https://github.com/HeavyIonAnalysis/AnalysisTree/blob/master/core/Track.cpp#L24
