### ISSUE TITLE
Variabl::GetValue relies on branch_id-s which can change under specific circumstances

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/AnalysisTree#57]
Dear Viktor,

https://github.com/HeavyIonAnalysis/AnalysisTree/blob/705e24af77c2747ed82eeb8cb92f0b9ddca19ee8/infra/Variable.hpp#L112

This function takes two data objects (e.g. EventHeaders) and two branch id-s to take value from either one branch or from another. As far as I understood, it makes sense for composite variables which can have (in principle) more than one branch.

**How the AT::Field gets branch_id**:

AT::Field gets branch_id during the call `AT::Field::Init(AT::Configuration)` from the corresponding `BranchConfig`. In turn, index of BranchConfig is selected by the `AT::Configuration` during `Configuration::AddBranchConfig`

**What is a_id  (b_id)**:

These arguments are taken from data pointers. Data pointers are taking their index at creation.

**What goes wrong**

`AnalysisTree::TaskManager` allows to take several input files (filelists) and merge branches of AT. Configuration is merged also. BranchConfig-s from many other configurations are added to the first one via `Configuration::AddBranchConfig`.

So what happens: 
Indexing of BranchConfig-s changed after merge.
Indexing in the data pointers doesn't change.

Surprisingly, this bug appears only when two branches are participating on one AnalysisTree::VarManagerEntry. In this case Field::GetValue decides, from which pointer it takes the value basing on branch ids. And throws:
https://github.com/HeavyIonAnalysis/AnalysisTree/blob/705e24af77c2747ed82eeb8cb92f0b9ddca19ee8/infra/Variable.hpp#L121

**Comment by eugene274** [comment]
Affected all versions and all projects based on AnalysisTree.

**Comment by eugene274** [comment]
For v1.0 fixed in #58

**Comment by eugene274** [comment]
@viktorklochkov Isn't it closed by #60

**Comment by viktorklochkov** [comment]
Yes, forgot to update.

closed by #60
